[package]
name = "fraud-scorer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fraud-common = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
ndarray = { workspace = true }
extended-isolation-forest = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }

[[bench]]
name = "scorer_bench"
harness = false
