[package]
name = "fraud-features"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fraud-common = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
ndarray = { workspace = true }
